version: 2

models:
  - name: stg_dummy__customers
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - customer_id
            - snapshot_dt
  - name: hist_customers
    columns:
      - name: customer_id
        tests:
          - tvf_unique:
              params: date "2023-01-02"
