version: 2

models:
  - name: stg_tvf
    description: your first tvf
    columns:
      - name: dt
        description: date
      - name: day_of_week
        description: 'Sun... 0, Sat... 6'
  - name: tvf
    description: your second tvf
    columns:
      - name: dt
        description: date
      - name: day_of_week
        description: 'Sun... 0, Sat... 6'
